### ISSUE TITLE
Palette to apply security theme to all endpoints

### ISSUE THREAD

**Issue by brasilikum** [mulesoft/api-workbench#125]
As there seems to be no possibility in the RAML Spec itself (correct me if I am wrong), it would be nice
if I could apply a security scheme to all endpoints, maybe via a button at palette.

**Comment by sichvoge** [comment]
you can; there is a root-level `securedBy` node.

For example:

```yaml
#%RAML 1.0
title: Security Schemes 
securitySchemes:
 - oauth_2_0:
securedBy: [ oauth_2_0 ]
```
