### ISSUE TITLE
"format" facet unrecognized for number/integer type properties

### ISSUE THREAD

**Issue by mutsys** [mulesoft/api-workbench#147]
after updating to 0.8.24, the use of the "format" facet with number or integer raises an error.

**example:**
```
types:
    foo:
        type: object
        properties:
            type: number
            format: int16
```
 raises the following error message:

```
Error: property offset range type has error:specifiying unknown facet:format
```

Oddly enough, when adding the facet to a number/integer property, the popup list of format values still appears and be used to make a selection.
