### ISSUE TITLE
Example view on the `Details` pane does not work when example defines array properties

### ISSUE THREAD

**Issue by szank** [mulesoft/api-workbench#174]
With this snippet : 
```
#%RAML 1.0
---
title: Test API

types:
    testType:
        properties:
            stringVal:
            arrayVal:
                type: string[]
        example:
            stringVal: test
            arrayVal: [test, test2]
```
The example field in the `Details` pane is empty. When i remove the ` arrayVal: [test, test2]` from the code, the example pane looks OK, but I am getting an error about missing field in the example ( which is correct behaviour ). Could you pleas fix it.
