### ISSUE TITLE
Using uses does not work at v0.8.28 and v0.8.29

### ISSUE THREAD

**Issue by KeiichiHirobe** [mulesoft/api-workbench#179]
There is a error at uses node when I upgrade to  v0.8.28 or v0.8.29.
It seems that using uses does NOT import the remote library assets into the local file.

The image below is screenshot of getting started examples

If my understanding is mistaken, please tell me.

![api](https://cloud.githubusercontent.com/assets/16670885/15502460/0b088f8c-21ef-11e6-8fe7-4bc018e8325c.png)

**Comment by ddenisenko** [comment]
The syntax should be supported in 0.8.29. This is a pre-release version, which can not be installed from inside Atom, the instructions in the build description need to be followed: https://github.com/mulesoft/api-workbench/releases/tag/v0.8.29

If installation of 0.8.29 was performed with accordance with instructions, please attach/post both master RAML and the library so we can check it locally.

**Comment by KeiichiHirobe** [comment]
Thanks for your reply.

I installed 0.8.29 following https://github.com/mulesoft/api-workbench/releases/tag/v0.8.29  before I posted, and tried installing again , but there is the same error as posted.

For your information, 

- There is NO error in NewLibrary.raml.
- The error of master RAML occured to my colleagues too.
- There is NO error in both of master RAML and NewLibrary.raml at v0.8.27.

Attached Files are both master RAML and the library.

[sample.zip](https://github.com/mulesoft/api-workbench/files/281374/sample.zip)

**Comment by ddenisenko** [comment]
Thank you for the sample.

Version 0.8.29 expects RAML 1.0 RC2/GA syntax for uses.

Replace 
`NewLibrary: !include NewLibrary.raml` with `NewLibrary: NewLibrary.raml`

**Comment by ddenisenko** [comment]
Please check https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#libraries for details of the new syntax.

**Comment by KeiichiHirobe** [comment]
Thank you for your reply.

I replaced as you said, errors of my sample files disapppeared.
I am sorry for my carelessness.

But, there are errors in my original files (not my sample files I posted)
at differrent places from before.

I have a question.
Listed files are new sample files to simulate error.

There is no error unless commenting out at line 5 in api.raml.
The error is  "inheriting from unknown typeat line 9 col 1".

So, why do I need "NewLibrary2: Newlibrary2.raml" in api.raml?
I could not understand the reason even though I checked
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#libraries .

At Version 0.8.27, there is no error in sample files.
(Of course, I replaced NewLibrary:!include NewLibrary.raml with  NewLibrary: NewLibrary.raml before check)

Is this a bug or intended behavior ?

Attached file is zip file of below.

**api.raml**

```
#%RAML 1.0
title: Pet shop
uses:
  NewLibrary: NewLibrary.raml
  NewLibrary2: NewLibrary2.raml # If comment-out this line, error occured.
version: 1
baseUri: /shop

/pets:
  type: NewLibrary.Pet_resourcetype
```
**NewLibrary.raml**

```
#%RAML 1.0 Library
uses:
  NewLibrary2: NewLibrary2.raml

resourceTypes:
  Pet_resourcetype:
    get:
      queryParameters:
        PET:
          type: NewLibrary2.Pet
```
**NewLibrary2.raml**
```
#%RAML 1.0 Library
types:
  Pet:
    discriminator: kind
    properties:
      name: string
      kind: string
      price: number
      color:
        enum:
          - White
          - Black
          - Colored
    example:
      name: Snoopy
      kind: Mammal
      price: 100
      color: White
```
[sample2.zip](https://github.com/mulesoft/api-workbench/files/284236/sample2.zip)
