### ISSUE TITLE
RC2: String (XML/JSON) examples are not displayed in Details for RAML 1.0

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#187]
RAML:

```
#%RAML 1.0
---
title: Test API

types:
    testType:
        properties:
            stringVal: string
        example: |
          {
            "stringVal": "test"
          }

```

Click on `testType`. 
Check `General` tab of `Details` view. There used to be a tree view for JSON examples there.

Same applies to multiple examples case and XML examples.
