### ISSUE TITLE
RC2: Pull up defaults to itself

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#192]
RAML:

```
#%RAML 1.0

title: test

types:
  User:
    properties:
      id: number
      first_name: string
      last_name: string
      email: string
  DefaultResponse:
    type: User
    properties:
      code:
        type: integer
      message:
        type: string
  UserDependentType:
    type: DefaultResponse
    properties:
      moreProp: number
      moreProp2: string

```

Put cursor at UserDependentType type. Activate "Pull up" action. 

Result: UserDependentType type is listed as a viable target and selected by default.
