### ISSUE TITLE
RC2: Extract super type action is not accessible

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#193]
RAML:

```
#%RAML 1.0

title: test

types:
  User:
    properties:
      id: number
      first_name: string
      last_name: string
      email: string
  DefaultResponse:
    type: User
    properties:
      code:
        type: integer
      message:
        type: string
  UserDependentType:
    type: DefaultResponse
    properties:
      moreProp: number
      moreProp2: string

```

Put cursor at User type. Extract Supertype action is not listed in "Refactoring" group of context menu.
