### ISSUE TITLE
RC2: Extract super type action explodes on pressing OK

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#194]
RAML:

```
#%RAML 1.0

title: test

types:
  User:
    properties:
      id: number
      first_name: string
      last_name: string
      email: string
  DefaultResponse:
    type: User
    properties:
      code:
        type: integer
      message:
        type: string
  UserDependentType:
    type: DefaultResponse
    properties:
      moreProp: number
      moreProp2: string

```

Put cursor at User type. Invoke `Extract Supertype` action and move `email` property to the right, type supertype name. Press the green button.

Result: exception.
