### ISSUE TITLE
Search does not work for facet properties

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#217]
RAML:

```
#%RAML 1.0

title: AA
types:
  FacetSuperType:
    type: object
    facets:
      testFacet2: string
  FacetType:
    properties:
      testFacetProp: string
  FirstType:
    properties:
      testprop: string
    facets:
      testFacet: FacetType
  SecondType:
    type: FirstType
    testFacet:
      testFacetProp: df
```

Invoke Open Declaration action for `testFacetProp` inside `SecondType`.

Result: nothing happens
Expected result: facet declaration is opened.
