### ISSUE TITLE
Details do not display type for a property having built-in facets

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#225]
RAML:

```
#%RAML 1.0

title: test

types:
  PropType:
    type: object
  PropType2:
    type: string
  TestType:
    type: object
    properties:
      numberProp1:
        type: number
        minimum: 10
      numberProp2: number
      numberProp3:
        type: number
      stringProp1:
        type: string
      stringProp2: string
      stringProp3:
        type: string
        minLength: 5
      objectProp1: PropType
      objectProp2: PropType2

```

Steps:

1. Put cursor at `TestType`
2. Open `Type` tab of details. 

Result: `numberProp1` and `stringProp3` have no type printed in the list of the properties, while other properties have types printed just fine.
