### ISSUE TITLE
Details corrupt the code when editing type shortcuts

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#226]
RAML:

```
#%RAML 1.0

title: test

types:
  PropType:
    type: object
  PropType2:
    type: string
  TestType:
    type: object
    properties:
      numberProp1:
        type: number
        minimum: 10
      numberProp2: number
      numberProp3:
        type: number
      stringProp1:
        type: string
      stringProp2: string
      stringProp3:
        type: string
        minLength: 5
      objectProp1: PropType
      objectProp2: PropType2

```

Steps:

1. Put cursor at `numberProp2`
2. Type a new type `boolean` in the `type` field in Details.

Result: Code is corrupted
Note: this works fine for `numberProp1` and others not using type shortcut.
