### ISSUE TITLE
For RAML 0.8 default parameter values are not validated against parameter types

### ISSUE THREAD

**Issue by KonstantinSviridov** [mulesoft/api-workbench#228]
For example, the parser produces no error for
```
#%RAML 0.8
title: test
/test:
  post:
    queryParameters:
      limit:
        type: integer
        default: asdasd
```
