### ISSUE TITLE
Issues with displaying examples in the `Details` tab

### ISSUE THREAD

**Issue by szank** [mulesoft/api-workbench#242]
Hi, 
Given this Api definition : 
```
#%RAML 1.0
---
title: Test API

types:
    testType:
        properties:
            stringVal:
            intVal: integer
            arrayVal:
                type: string[]
        example:
            stringVal: test
            intVal: 10 
            arrayVal: [test, test2]
```
I have noticed some issues with viewing the examples. I have api-workbench ver 0.8.32

1. 
<img width="806" alt="screenshot 2016-06-27 11 36 49" src="https://cloud.githubusercontent.com/assets/773802/16377162/54445032-3c5c-11e6-83f9-4f87d87a1dc6.png">
There example value for `intVal` is not displayed 

2. 
This is a strange error I see when clicking on the `- example` in the outline view. The error can be seen in the Details view. 
<img width="816" alt="screenshot 2016-06-27 11 37 44" src="https://cloud.githubusercontent.com/assets/773802/16377232/c45901f6-3c5c-11e6-8a5c-9d1ef01c6d14.png">
