### ISSUE TITLE
Example not displayed at all when the type contains an integer array 

### ISSUE THREAD

**Issue by szank** [mulesoft/api-workbench#243]
given those two types: 

```
#%RAML 1.0
---
title: Test API

types:
    testIntArrayType:
        properties:
            arrayVal:
                type: integer[]
        example:
            arrayVal: [10, 20]

    testStringArrayType:
        properties:
            arrayVal:
                type: string[]
        example:
            arrayVal: ["10", "20"]
```
The example for type `testIntArrayType` is not displayed at all in the `Details` view, while the example for the type `testStringArrayType`  is displayed properly.
