### ISSUE TITLE
Auto-completion for properties is broken when defining a sequence / array in an example

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#278]
When defining an example for an array, the auto-completion does not give me the suggestions for any of the properties that i have defined. See the following example and try to add a new item to the `idealDrinks` example:

```yaml
types:
  Bean:
    properties:
      id: string
      name: string
      originRegion: string
      originCountry: string
      idealDrinks:
        type: array
        items: IdealDrink
    example:
      id: "001"
      name: "Arid Aribica"
      originRegion: "Latin America"
      originCountry: "Columbia"
      idealDrinks:
        - drinkID: "100"
          drinkName: ""
          drinkTemp: ""
  IdealDrink:
    properties:
      drinkID: string
      drinkName: string
      drinkTemp: string
```
