### ISSUE TITLE
Empty list in YAML doesn't translate properly in examples

### ISSUE THREAD

**Issue by asthasr** [mulesoft/api-workbench#289]
I am attempting to use YAML to make my examples composable. However, the API console doesn't seem to properly interpret the `[]` for empty lists; it shows up in the console example as `null` in my JSON example.

To duplicate, create an example node with an `!include` of a RAML file that has a `foo: []` key.

**Comment by ddenisenko** [comment]
Could you please attach RAML and YAML code to reproduce?

I used the following:
main.raml:
```
#%RAML 1.0
title: New API
version: v1
baseUri: http://api.samplehost.com

/test:
  post:
    body:
      application/json:
        example: !include test51YAML.yaml
```

test51YAML.yaml:
```
foo: []
```

Resulting console screenshot:
![consoleyamlarray](https://cloud.githubusercontent.com/assets/14824966/18574654/32c2c466-7bf9-11e6-96b3-6a91304b1c5e.png)
