### ISSUE TITLE
2 files that include each other causes a maximum call stack exceeded

### ISSUE THREAD

**Issue by redndahead** [mulesoft/api-workbench#29]
If I have one file that has:

```
#%RAML 1.0 Library
uses:
  - File2: !include file2.raml

types:
  Base:
    type: object
    properties:
      name: string
  Full:
    type: Base
    properties:
      file2s: File2.Base[]
```

Another one that has:

```
#%RAML 1.0 Library
uses:
  - File1: !include file1.raml

types:
  Base:
    type: object
    properties:
      name: string
  Full:
    type: Base
    properties:
      file1: File1.Base
```

You'll get this error: https://www.evernote.com/l/AJV4gePtO9BHEYHlmFN9Lnw6SDLeunSmwx0

I'm not sure if this isn't ok in the spec or if it's just a bug in the editor.
