### ISSUE TITLE
Additional properties defined by "//" do not work with other properties. 

### ISSUE THREAD

**Issue by marticka** [mulesoft/api-workbench#296]
I would like to declare a type with one fixed property and force any additional property to be a string. I tried the approach from the documentation (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#additional-propertie). An error has occurred: map property mapPropertyIs conflicts with property:boolVar. 
```
#%RAML 1.0
---
title: Test API

types:
   typeOne:
      properties:
         boolVar:
             type: boolean
         //:
           type: string
```
What is then the correct approach?

**Comment by sichvoge** [comment]
Can you let me know what version of the api-workbench you use?

**Comment by ddenisenko** [comment]
The error you see will be converted to a warning in the next release, but it is still recommended to not to have pattern properties to conflict with explicitly named properties.

You can make the  pattern to exclude explicitly named properties like this: `/^!(boolVar)$/`

**Comment by marticka** [comment]
I use version **0.8.35.**

**Comment by marticka** [comment]
According to **RAML 1.0 documentation**, this should work:
```
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      //: # force all additional properties to be a string
        type: string
```
