### ISSUE TITLE
Validation error when including rfc2161 datetime values in included json examples

### ISSUE THREAD

**Issue by howzat** [mulesoft/api-workbench#329]
Reading through the docs, I think this should work. Given the following two files (test.raml and test.json) the workbench reports "Valid rfc2616 formatted string is expected".  Thanks!

test.raml
```
#%RAML 1.0 Library
usage: |
  Exposition
types:

  Test:
    type: object
    properties:
      t:
        type: datetime
        format: rfc2616
     example: !include test.json
```
test.json
```
{
  "t": "Sat, 8 Oct 2016 20:04:37 GMT" // this is a valid rfc2616 datetime
}
```
[Archive.zip](https://github.com/mulesoft/api-workbench/files/518398/Archive.zip)
