### ISSUE TITLE
`TypeError: Cannot read property 'absolutePath' of null` when !include path not exist

### ISSUE THREAD

**Issue by reorx** [mulesoft/api-workbench#368]
The error log is like:

```
TypeError: Cannot read property 'absolutePath' of null
    at NamespaceResolver.nsMap (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/namespaceResolver.js:177:28)
    at ReferencePatcher.resolveReferenceValueBasic (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:363:38)
    at ReferencePatcher.resolveReferenceValue (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:329:29)
    at ReferencePatcher.patchType (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:264:44)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:81:18)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.process (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:35:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:113:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:91:27)
    at Object.expandTraitsAndResourceTypes (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:27:10)
    at ASTNodeImpl.validate (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:927:35)
    at c (/Users/reorx/.atom/packages/api-workbench/main.js:2:5647)
    at u (/Users/reorx/.atom/packages/api-workbench/main.js:2:5369)
    at Object.p [as lint] (/Users/reorx/.atom/packages/api-workbench/main.js:2:4693)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/reorx/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/reorx/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/reorx/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/reorx/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/reorx/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/reorx/.atom/packages/linter/lib/helpers.coffee:25:18
```

When editing and saving a file like this:

```
#%RAML 1.0
---
title: Foo API
version: 0.1.0
protocols: HTTPS
mediaType: application/json
baseUri: https://example.com

traits:
  bar:
    usage: bar usage

/baz:
  post:
    body:
      type: !include path/not/exist.json
```

But if `traits` is removed, api-workbench will work normally, with syntax lint showing at the bottom:

```
#%RAML 1.0
---
title: Foo API
version: 0.1.0
protocols: HTTPS
mediaType: application/json
baseUri: https://example.com

/baz:
  post:
    body:
      type: !include path/not/exist.json
```

![image](https://cloud.githubusercontent.com/assets/405972/21427751/5097599a-c891-11e6-8a1d-5129e75b2f85.png)

Tested under: OS X 10.11.6, Atom 1.12.7, api-workbench 0.8.40
