### ISSUE TITLE
Datetime attribute example validation fails if the value contains microseconds

### ISSUE THREAD

**Issue by kuba-gasiorowski** [mulesoft/api-workbench#395]
The datetime type requires the value in the format defined by RFC3339 (unless specified explicitly RFC2616):
> A timestamp in one of the following formats: if the format is omitted or set to rfc3339, uses the "date-time" notation of RFC3339; if format is set to rfc2616, uses the format defined in RFC2616

RFC3339 does not limit the fractional part of the second to any specific granularity:
```
time-secfrac    = "." 1*DIGIT
```
 However, when providing example value of the datetime attribute with microseconds API shows the error:
```
Valid rfc3339 formatted string is expected at line 10 col 5
```
Please consider following example to reproduce:
```
#%RAML 1.0
title: Datetime format
mediaType: application/json
types:
  bugType:
    type: object
    properties:
      modified:
        type: datetime
    example: |
      {
        "modified": "2017-01-20T09:25:00.000000+01:00"
      }
```
Changing the example value containing milliseconds only makes the definition valid.
However, any fractional part of the second should be allowed, according to the specification.
