### ISSUE TITLE
Parameter values not parsed correctly by console

### ISSUE THREAD

**Issue by comikem** [mulesoft/api-workbench#403]
Version 0.8.42
When using substitution parameters the console will now parse the value.  <> will be displayed instead of the value of <<resourcePathName>> for example

```
/contacts:
  description: Access <<resourcePathName>> objects
  get:
    description: Return a list of<<resourcePathName>>
```
Will display as: 

![image](https://cloud.githubusercontent.com/assets/18690628/22567236/68862852-e94c-11e6-9b0c-e8b9f0788e0d.png)

![image](https://cloud.githubusercontent.com/assets/18690628/22567241/6de933de-e94c-11e6-9ad3-67ae907049da.png)
