### ISSUE TITLE
Cannot use annotation types as types in annotations

### ISSUE THREAD

**Issue by oberlies** [mulesoft/api-workbench#422]
Despite the design principle "annotations are just types", I cannot use annotation types as types in annotation definitions.

Example: This yields the (incomplete?) error message "Component type has error:" in the current API workbench (0.8.43)
```
#%RAML 1.0
title:
documentation:
  - title: Section
    content: Text in section
    (subsections):
      - title: Sub-section
        (subsections):
          - title: Sub-sub-section
            content: Text in sub-sub-section
annotationTypes:
  subsections:
    allowedTargets: DocumentationItem
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
        content:
          type: string
          required: false
        (subsections):
          type: subsections
```
whereas the following definition works:
```
#%RAML 1.0
title:
documentation:
  - title: Section
    content: Text in section
    (subsections):
      - title: Sub-section
        (subsections):
          - title: Sub-sub-section
            content: Text in sub-sub-section
annotationTypes:
  subsections:
    allowedTargets: DocumentationItem
    type: subsectionsType
types:
  subsectionsType:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
        content:
          type: string
          required: false
        (subsections):
          type: subsectionsType
          required: false
```

The same problem occurs in non-recursive reuse.

IMHO it should be possible to re-use (other or the same) annotation types in annotation type definitions. In the current state, I have to pollute the types section with meta types to enable reuse.
