### ISSUE TITLE
Anchors on queryParameters/uriParameters parameter names lead to parser error

### ISSUE THREAD

**Issue by oberlies** [mulesoft/api-workbench#435]
Instead of writing
```
#%RAML 1.0
title: Anchor breaks queryParameter/uriParameter type parsing
/resource1:
  get:
    queryParameters:
      filter:
        type: string
        description: An identifier with...
/resource2:
  get:
    queryParameters:
      filter:
        type: string
        description: An identifier with...
```
I should be able to reduce redundancy by using a YAML anchors and references:
```
#%RAML 1.0
title: Anchor breaks queryParameter/uriParameter type parsing
/resource1:
  get:
    queryParameters:
      filter: &filterRef
        type: string
        description: An identifier with...
/resource2:
  get:
    queryParameters:
      filter: *filterRef
```
However this results in the a parser error marker in the type line: "Inheriting from unknown type". So the presence of the anchor seems to break the type parsing.

The anchor works when I put in on the queryParameters element directly, but then I cannot re-use parameters individually, e.g.
```
queryParameters:
  filter: *filterRef
  page: *pageRef
```
