### ISSUE TITLE
Rename adds a redundant ending in a certain case

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#467]
```
#%RAML 1.0
title: test
types:
  NewTestType:
    type: object
    properties:
      field: string
    example:
      field: value
resourceTypes:
  TestResorceType:
    post:
      description: Allows to create new <<objectName | !singularize>>
      body:
        application/json:
          type: <<objectName | !singularize>>
/test:
  type:  { TestResorceType: {objectName : NewTestType} }
```

Set cursor at the line 11 `TestResorceType:`-> Context menu -> Rename symbol -> Paste a new resource type name `TestResorceType5:` -> Press enter.

Result: 

```
#%RAML 1.0
title: test
types:
  NewTestType:
    type: object
    properties:
      field: string
    example:
      field: value
resourceTypes:
  TestResorceType5:
    post:
      description: Allows to create new <<objectName | !singularize>>
      body:
        application/json:
          type: <<objectName | !singularize>>
/test:
  type:  { TestResorceType55: {objectName : NewTestType} }

```
