### ISSUE TITLE
No opening square bracket is added on completion in a certain case

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#468]
In VS Code client:

```
#%RAML 1.0
title: test
traits:
  TestTrait:
    queryParameters:
      limit:
        type: integer
        default: <<limitDefault>>
/test:
  get:
```

The order of typing is important.

Type new line after `get:`, 2 spaces, `i`. 
Completion suggests `is:`, press enter to intsert the suggestions.
Now, start typing `T`.
Completion suggests `TestTrait`, press enter to insert the suggestion.

Result:
```
#%RAML 1.0
title: test
traits:
  TestTrait:
    queryParameters:
      limit:
        type: integer
        default: <<limitDefault>>
/test:
  get:
    is: TestTrait: {limitDefault : }]
```

Notice no opening square barcket: `    is: [TestTrait: {limitDefault : }]` should be instead.
