### ISSUE TITLE
Error with type "file" and specified "fileTypes"

### ISSUE THREAD

**Issue by ValeryVS** [mulesoft/api-workbench#477]
Example
```
#%RAML 1.0 Library
types:
  SmallImage:
    type: object
    properties:
      type:
        type: string
        description: MIME-type
      data:
        type: file
        fileTypes:
          - "image/jpeg"
          - "image/png"
        maxLength: 307200
        description: Base64 image
    example:
      data: "somefileencodedinbase64=="
      type: "image/png"
```

Type is OK, but error is shown for "data" field of example.
```
'fileTypes' value should be an array of strings.
```
