### ISSUE TITLE
Annotations with "type: array" are not validated

### ISSUE THREAD

**Issue by oberlies** [mulesoft/api-workbench#67]
When using annotations with a parameter of `type: array`, the validator ignores errors in that parameter.

Example: This correctly yields a validation error ("unknown node:foo")

```
#%RAML 1.0
title:
documentation:
  - title: Section
    (contents):
      value:
        - title: Sub-section
          content: some content
          foo: unknown tag
annotationTypes:
  contents:
    parameters:
      value:
        type: contentAnnotationParam[]
types:
  contentAnnotationParam:
    type: object
    properties:
      title: string
      content: string
```

... but the following equivalent annotation parameter type declaration does not yield a validation error:

```
#%RAML 1.0
title:
documentation:
  - title: Section
    (contents):
      value:
        - title: Sub-section
          content: some content
          foo: unknown tag
annotationTypes:
  contents:
    parameters:
      value:
        type: array
        items:
          type: object
          properties:
            title: string
            content: string
```

The behaviour of the validator should be the same in both cases.

As shown in the example, it is possible to work around this problem. This however requires that the array item type is declared in the `types` section, so we end up with mixture of API types is and meta types.

**Comment by ddenisenko** [comment]
@oberlies Thanks for reporting this.

It looks like this is a more general validation problem.

In example, in the following code "foo" is only reported in the last case:

```RAML
types:
  TestType:
    type: array
    items:
      type: object
      properties:
        title: string
        content: string
    example: 
      - title: blah
        content: blah
        foo: test
  TestType2:
    properties:
      title: string
      content: string
  TestType3:
    type: array
    items: 
      type: TestType2
    example: 
      - title: blah
        content: blah
        foo: test
  TestType4: TestType2[]
  TestType5:
    type: TestType4
    example: 
      - title: blah
        content: blah
        foo: test
```

**Comment by oberlies** [comment]
This issue seems to have been resolved. With the annotationType syntax of the current RAML 1.0 spec, the API definition would look like this:
```
#%RAML 1.0
title:
documentation:
  - title: Section
    content:
    (contents):
      - title: Sub-section
        content: some content
        foo: unknown tag
annotationTypes:
  contents:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        title: string
        content: string
```
In this specification, the API workbench 0.8.43 correctly detects the "Unknown property: 'foo'"
