### ISSUE TITLE
Annotations with "additionalProperties" are not validated

### ISSUE THREAD

**Issue by oberlies** [mulesoft/api-workbench#68]
When using annotations with a parameter of type object, the constraints imposed by `additionalProperties` are not checked by the validator.

Example: This declaration correctly yields a validation error ("unknown node:foo")

```
#%RAML 1.0
title:
(errors):
  value:
    invalidRequestBody:
      httpStatus: 400
      description: The request body is not a JSON object
      foo: unknown tag
annotationTypes:
  errors:
    parameters:
      value:
        type: object
        properties:
          []:
            type: object
            properties:
              httpStatus: number
              description: string
```

... but the following equivalent type declaration does not yield a validation error:

```
#%RAML 1.0
title:
(errors):
  value:
    invalidRequestBody:
      httpStatus: 400
      description: The request body is not a JSON object
      foo: unknown tag
annotationTypes:
  errors:
    parameters:
      value:
        type: object
        additionalProperties:
          type: object
          properties:
            httpStatus: number
            description: string
```

The behaviour of the validator should be the same in both cases.

**Comment by ddenisenko** [comment]
Reproducible.

**Comment by oberlies** [comment]
Curiously, the expected validation error "unknown node:foo" can also be triggered by declaring the parameter value to be an array (!) of the additional properties type:

    #%RAML 1.0
    title:
    (errors):
      value:
        invalidRequestBody:
          httpStatus: 400
          description: The request body is not a JSON object
          foo: unknown tag
    annotationTypes:
      errors:
        parameters:
          value:
            type: errorsAnnotationParam[]
    types:
      errorsAnnotationParam:
        type: object
        properties: 
          httpStatus: number
          description: string

**Comment by oberlies** [comment]
This bug report is obsolete because the additionalProperties syntax was changed in one of the later RAML 1.0 version.

additionalProperties now takes a boolean instead of an object, and the `[]` placeholder was replaced with patterns enclosed in slashes.

So the new (and AFAIK only) specification in the current RAML 1.0 version to get the "Unknown property: 'foo'" error is
```
#%RAML 1.0
title:
(errors):
  invalidRequestBody:
    httpStatus: 400
    description: The request body is not a JSON object
    foo: unknown tag
annotationTypes:
  errors:
    type: object
    properties:
      //:
        type: object
        additionalProperties: false
        properties:
          httpStatus: number
          description: string
```
This error is correctly detected by the API workbench 0.8.43.
