### ISSUE TITLE
Error: Recurrent type definition

### ISSUE THREAD

**Issue by redndahead** [mulesoft/api-workbench#83]
I was playing around with types and I ran into this issue. Is this not allowed?

Given:
test.raml
````
#%RAML 1.0 Library
uses:
  ld: !include test2.raml

types:
  Post:
    type: object
    properties:
      name: string
  Base:
    type: [ld.Base, Post] <--- Error shown on this line
    properties:
      id: string
````

and

test2.raml
````
#%RAML 1.0 Library
types:
  Base:
    type: object
    properties:
      "@id": string
      "@type": string
````
