### ISSUE TITLE
Outline does not show inherited properties

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#84]
using that type example:

```yaml
types:
  # Properties common to all imagery providers.
  BaseProperties:
    properties:
      acquired: date
  # Properties specific to one imagery provider.
  PlanetProperties:
    type: BaseProperties
    properties:
      vnd_camera_gain:
        type: number
        minimum: 0
```

I am getting only that inside my outline:

![image](https://cloud.githubusercontent.com/assets/498114/11973825/677ea236-a956-11e5-8926-921e0e7732d6.png)

Not sure what generally is expected, but I would expected to also see `acquired` inherited from the `BaseProperties` class.

The console for example is showing what I would expect

![image](https://cloud.githubusercontent.com/assets/498114/11973907/19acce2e-a957-11e5-9249-bd6f9dca4b7f.png)
